-- ICON-NUST MySQL schema.
-- Apply with: mysql -u <user> -p <database> < lib/db/schema.sql
-- (or node --env-file=.env.local scripts/apply-schema.mjs)

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(200) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(150) NOT NULL DEFAULT 'Admin',
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  otp_code_hash VARCHAR(255) NULL,
  otp_expires_at DATETIME NULL,
  otp_attempts INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_admins_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invention_disclosures (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source ENUM('idf-modal', 'quick-form') NOT NULL,
  invention_title VARCHAR(300) NOT NULL,
  domain VARCHAR(200) NOT NULL DEFAULT '',
  inventor_names VARCHAR(300) NOT NULL DEFAULT '',
  department VARCHAR(200) NOT NULL DEFAULT '',
  student_or_employee_id VARCHAR(100) NOT NULL DEFAULT '',
  contact_email VARCHAR(200) NOT NULL,
  contact_phone VARCHAR(50) NOT NULL DEFAULT '',
  conception_date VARCHAR(50) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  novelty TEXT NULL,
  applications TEXT NULL,
  funding_source VARCHAR(300) NOT NULL DEFAULT '',
  prior_disclosure ENUM('yes', 'no') NOT NULL DEFAULT 'no',
  prior_disclosure_details TEXT NULL,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  display_status VARCHAR(100) NOT NULL DEFAULT '',
  trl VARCHAR(20) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_disclosures_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS home_inquiries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  domain VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NULL,
  status ENUM('new', 'read') NOT NULL DEFAULT 'new',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_home_inquiries_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS industry_service_inquiries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  domain VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NULL,
  status ENUM('new', 'read') NOT NULL DEFAULT 'new',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_industry_service_inquiries_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS innovation_inquiries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  domain VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NULL,
  status ENUM('new', 'read') NOT NULL DEFAULT 'new',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_innovation_inquiries_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS team_members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  title VARCHAR(200) NOT NULL,
  dept VARCHAR(200) NOT NULL,
  bio TEXT NOT NULL,
  focus JSON NOT NULL,
  image VARCHAR(500) NOT NULL,
  email VARCHAR(200) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  tag VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  founder VARCHAR(200) NOT NULL,
  funding VARCHAR(100) NOT NULL,
  image VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  day VARCHAR(10) NOT NULL,
  month VARCHAR(20) NOT NULL,
  year VARCHAR(10) NOT NULL,
  title VARCHAR(300) NOT NULL,
  type VARCHAR(100) NOT NULL,
  location VARCHAR(300) NOT NULL,
  description TEXT NOT NULL,
  registered INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(300) NOT NULL,
  slug VARCHAR(300) NOT NULL,
  category VARCHAR(150) NOT NULL,
  excerpt TEXT NOT NULL,
  content JSON NOT NULL,
  image VARCHAR(500) NOT NULL,
  date VARCHAR(50) NOT NULL,
  read_time VARCHAR(20) NOT NULL DEFAULT '3 min',
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_news_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
